### ISSUE TITLE
Hi - A friendly message from the staff at discvent

### ISSUE THREAD

**Issue by webtax-gh** [6uv/Auto-discvent-winner#1]
We feel disappointed in you for cheating in a event meant to spread the love of the holiday season. We have reported your discord account for self-botting, and reported your github account. We are sorry that you feel to cheat in a way like this.

And as always, happy holidays! ❤️

**Comment by 6uv** [comment]
Never told people to use this

cant get my github removed for this lol + been disabled 14 times nothing special

And as always, happy holidays! ❤️ xoxo

**Comment by webtax-gh** [comment]
Hey!

This you? https://cdn.discordapp.com/attachments/789649120846676009/789649351290519572/AA7BBDE0-09F1-40A6-9154-B8E51211D5F9.png

And have a wonderful holiday season :heart:!

**Comment by 6uv** [comment]
It is!

Might want to utilize server folders!

And have a wonderful holiday season ❤️! xoxo

**Comment by undeadf0x** [comment]
you're just a dirty cheater,
aren't you?
yeah, get outta here.

**Comment by 6uv** [comment]
your in my github if you dont like it leave

**Comment by tandpfun** [comment]
eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by webtax-gh** [comment]
> 
> 
> your in my github if you dont like it leave

you're*

**Comment by undeadf0x** [comment]
:D
you're in the discvent server, if you don't l- oh wait :D (yeah i wouldn't cheat in events anymore if i were you)

**Comment by cheeziess** [comment]
imagine cheating

**Comment by undeadf0x** [comment]
absolute unpog my friend, you could be using your coding skills for ANYTHING ELSE
LITERALLY ANYTHING ELSE
yet you chose to code a cheating bot
**_much disappoint_**

**Comment by tandpfun** [comment]
much email

**Comment by undeadf0x** [comment]
and why, might i ask, good sir, are you getting emails from this repository? 
**_HMMMMM???_**

**Comment by conpatto** [comment]
Why are all you mad🤣🤣

**Comment by undeadf0x** [comment]
> Why are all you mad🤣🤣

don't even get me started
I COULD MAKE A GODDAMN LIST ABOUT WHY WE'RE MAD

**Comment by 6uv** [comment]
lol yall pissy asf today its 5$ nitro dude get a job, And ion get emails lol

**Comment by anishanne** [comment]
> lol yall pissy asf today its 5$ nitro dude get a job, And ion get emails lol

Yah bro, get a job stop spending your time making self bots so you can earn $5 nitro LOL.

**Comment by 6uv** [comment]
I never used it, Again its for fun :)

**Comment by tandpfun** [comment]
You were literally banned for using it

**Comment by cheeziess** [comment]
you make it public

**Comment by 6uv** [comment]
¯\_(ツ)_/¯

**Comment by 6uv** [comment]
> Yah bro, get a job stop spending your time making self bots so you can earn $5 nitro LOL.

I do have a job, Its winer break, Just for funzys

**Comment by anishanne** [comment]
yah bro winer break so fun bro winer!!!!!

**Comment by 6uv** [comment]
Also, Only like 1 person got nitro out of the candys, And now that this is out they will stop botters, You are spending the money on the giveaways not the candys. Your event is fine stop complaining, Your still making your money off these kids with youtube videos. Hate me all you want report me all you want It aint gunna change it. Just get use to the harsh reality.

And as always, happy holidays! ❤️ xoxo

**Comment by Masks1337** [comment]
LMAO rezizitw

**Comment by 6uv** [comment]
DUBB
