### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by RJain12** [6uv/Auto-discvent-winner#4]
lol we patched

**Comment by cheeziess** [comment]
lmfao

**Comment by 6uv** [comment]
Oh just wait :)

**Comment by 6uv** [comment]
+ also adding more invis characters is not really a patch

**Comment by anishanne** [comment]
If you're unable to bypass it I'm gonna go ahead and call it a patch LOL.

**Comment by RJain12** [comment]
even if they do bypass it (which they won't) we have images... these guys aren't smart enough for image recognition

**Comment by 6uv** [comment]
Oh no! it looks like it works now! 👍 
merry christmas

**Comment by 6uv** [comment]
also still waiting for image recognition ;)

**Comment by anishanne** [comment]
did u realize that candy drops for discvent 2020 are over kek

**Comment by 6uv** [comment]
that why i finally posted it 5 head

**Comment by RJain12** [comment]
and did you end up getting nitro? no. nice try though

**Comment by 6uv** [comment]
oh you think that was a rando who won? LMFAO

**Comment by RJain12** [comment]
there were 23 people who bought nitro, and we already know that you didn't get it

**Comment by Fweak** [comment]
You all are still on with this? If you say rezizt didn't get nitro then leave it at that.

**Comment by Fweak** [comment]
There's literally no more argument here. As what was done is done, and now the event is over.

**Comment by 6uv** [comment]
mans HELLA mad lol

**Comment by RJain12** [comment]
you spent hours for animated emotes and a GIF profile pic... good job LOL

**Comment by 6uv** [comment]
I alr have 14 months of nitro lul

**Comment by RJain12** [comment]
yeah so you wasted ur time good job

**Comment by 6uv** [comment]
hmm not really, it was  fun project to make

**Comment by Fweak** [comment]
@RJain12, can I get unbanned from your server :)

**Comment by RJain12** [comment]
You think I can't see what you all say in Visary? 👀 Yeah no, I'm not unbanning you.

**Comment by Fweak** [comment]
> You think I can't see what you all say in Visary? 👀 Yeah no, I'm not unbanning you.

I don't even say anything in Visary about or towards you.

**Comment by RJain12** [comment]
Still not going to unban people who use selfbots and like raiding 😎

**Comment by Fweak** [comment]
Sheesh good thing I do none of those.

**Comment by RJain12** [comment]
Strange considering you literally admitted to using a selfbot...
